### ISSUE TITLE
Get Wallet address and balance by keys 

### ISSUE THREAD

**Issue by GoNextGroup** [radianceteam/everscale-client-dotnet#3]
Sorry, earlier I asked this question in FreeTON github, but they gave me no answer. Maybe, you could do this?
I'm a newbie in TON usage. I'm trying to understand how to get my own wallet address, when I generate my wallet phrase? I have phrase, I can get public and private keys, but not a wallet address/balance.(( Could you explain me this with your cool library? Is it possible? Thank you.

**Comment by andy-a-o** [comment]
@GoNextGroup sorry you should get answer from the freeton team, here we're expecting to have bug reports/improvement suggestions only.
